---
kc_source:
 url: https://box.eadn.dz/kcx20
 username: admin
 password: blahblah
 realm: EADN-REALM
 clients:
   - eadn-client-local
   - eadn-client
   - eadn-client-asso-prod
   - eadn-client-local-asso
   - asso-prod
   - rh-prod
 roles:
   - asso_user
   - asso_prod_user
   - at_user
 groups:
   - ADMIN
   - association_groups

kc_target:
 url: https://demo.eadn.dz/dgb_auth
 username: admin
 password: blahblah
 realm: Go-Realm
 clients:
   - eadn-client-local
   - eadn-client
   - eadn-client-asso-prod
   - eadn-client-local-asso
   - asso-prod
   - rh-prod
 roles:
   - asso_user
   - asso_prod_user
   - at_user
 groups:
   - ADMIN
   - association_groups
