---
kc_source:
 url: https://box.eadn.dz/kcx20
 username: admin
 password: Azerty123654
 realm: EADN-REALM
 clients:
   - asso-prod
   - rh-prod
 roles:
   - asso_user
   - at_user
 groups:
   - ADMIN

kc_target:
 url: https://demo.eadn.dz/dgb_auth
 username: admin
 password: Azerty123
 realm: Go-Realm
 clients:
   - asso-prod
   - rh-prod
 roles:
   - asso_user
   - at_user
 groups:
   - ADMIN
