---
kc_source:
 url: https://auth.eadn.dz/auth
 username: admin
 password: blahblah
 realm: INVEST-REALM
 clients:
   - invest-backend
   - invest-frontend
 roles:
   - invest_user
 groups:
   - invest_groups

kc_target:
 url: https://demo.eadn.dz/dgb_auth
 username: admin
 password: blahblah
 realm: Go-Realm
 clients:
   - invest-backend
   - invest-frontend
 roles:
   - invest_user
 groups:
   - invest_groups
