---
kc_source:
 url: https://demo.blah.dz/dgb_auth
 username: admin
 password: blahblah
 realm: DGB-REALM
 clients:
   - dgb-pemp-backend
   - dgb-pemp-frontend
 roles:
   - frontend_realm_role
   - backend_realm_role
 groups:
   - dgb_pemp_groups

kc_target:
 url: https://box.blah.dz/kcx20
 username: admin
 password: blahblah
 realm: Go-Realm
 clients:
   - dgb-pemp-backend
   - dgb-pemp-frontend
 roles:
   - frontend_realm_role
   - backend_realm_role
 groups:
   - dgb_pemp_groups
